# --- 기본 메타 ---
name: 혜풍화창 Tech n Devlog
description: Software Artist, Fullstack Developer
avatar: "./images/IMG_4222.jpg"

footer-links:
  github: "hyefengtech"   # 아이콘은 username만으로도 충분
  rss: true

disqus:
google_analytics:

navigation:
  - name: Categories
    url: /
  - name: About
    url: /about
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags
  - name: Search
    url: /search/

paginate: 5
paginate_path: "/page:num/"

url: "https://hyefengtech.github.io"
baseurl: ""
permalink: /:title/
timezone: Asia/Seoul
lang: ko

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# collections / defaults 기존 커스텀은 일단 비활성(꼬임 방지)
# 필요해지면 나중에 다시 킴
# collections: {}
# defaults: []

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .idea

version: v1.2.0

